name: madsocialproj2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  firebase_auth: '>=4.17.8'
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  news_api_flutter_package: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
